# Generated by Django 2.1.7 on 2019-02-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='praise',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='shoe',
            new_name='shoe_name',
        ),
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='brand',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
